export const GAME_MODEL = Object.freeze({
  version: 'game-prototype-v1',
  rulesetVersion: 'game-rules-prototype-v1',
  battedBallVersion: 'batted-ball-prototype-v1',
  datasetVersion: 'fictional-game-fixture-v1',
  regulationInnings: 9,
  maximumInnings: 12,
  maxGamePitches: 10000,
  maxAppearancePitches: 100,
  starterPitchLimit: 90,
  relieverPitchLimit: 50,
  gravityMetersPerSecond2: 9.81,
  airborneDragFactor: 0.72,
  fenceCenterMeters: 120,
  fenceCornerMeters: 100,
  fenceHeightMeters: 3,
  baseDistanceMeters: 27.432,
  exitSpeedBaseKph: 70,
  exitSpeedPowerKph: 55,
  exitSpeedPitchFactor: 0.16,
  exitSpeedNoiseKph: 24,
  angleMinimumDegrees: -12,
  angleSpanDegrees: 90,
  runnerBaseMetersPerSecond: 5,
  runnerAbilityMetersPerSecond: 4,
  fielderReactionBaseSeconds: 0.65,
  fielderReactionReductionSeconds: 0.25,
  throwBaseMetersPerSecond: 20,
  throwAbilityMetersPerSecond: 15,
} as const);

export const FIELD_POSITIONS = Object.freeze({
  P: { x: 0, y: 18.44 },
  C: { x: 0, y: -1 },
  '1B': { x: 24, y: 24 },
  '2B': { x: 15, y: 37 },
  '3B': { x: -24, y: 24 },
  SS: { x: -15, y: 37 },
  LF: { x: -57, y: 70 },
  CF: { x: 0, y: 88 },
  RF: { x: 57, y: 70 },
});
